BEGIN;

ALTER TABLE app_users
ADD COLUMN IF NOT EXISTS avatar_url TEXT;

ALTER TABLE app_role_permissions
ADD COLUMN IF NOT EXISTS sort_order INTEGER NOT NULL DEFAULT 0;

ALTER TABLE reservations
ADD COLUMN IF NOT EXISTS sort_order INTEGER NOT NULL DEFAULT 0;

COMMIT;
